### ISSUE TITLE
Linting does not work in VSCode ver 1.44.0

### ISSUE THREAD

**Issue by yamitake** [aliariff/vscode-slim-lint#3]
This extension is useful and very helpful, but I don't think it will work with the versions below. Can you handle it?

```
Version: 1.44.0
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-08T08:23:56.137Z (5 days ago)
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

**Comment by aliariff** [comment]
Hi @yamitake 

could you try again?

**Comment by yamitake** [comment]
@aliariff 

Thank you for updating. I tried it but it didn't work. Am I missing something?
Is there any information I can provide?

By the way, I am developing Rails. and I can run slim-lint from terminal.

### vs code info
```
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z (6 days ago)
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

### and extensions
![スクリーンショット 2020-04-24 1 10 00](https://user-images.githubusercontent.com/815640/80122420-7d474e80-85c8-11ea-955b-9539bb473980.png)

**Comment by aliariff** [comment]
Hi @yamitake 

Could you show me the output from `Help -> Toggle Developer Tools` ?

**Comment by yamitake** [comment]
Hi @aliariff 

Thank you for your help.
I have found errors and warnings in the developer tools console screen.
I did some research but couldn't solve it.

If this is an OS issue, close this issue.

#### Warning
```
Overwriting grammar scope name to file mapping for scope source.ruby.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/ruby/syntaxes/ruby.tmLanguage.json.
New grammar file: file:///Users/jj/.vscode/extensions/wingrunr21.vscode-ruby-0.27.0/syntaxes/ruby.cson.json
register @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4414
2/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1611 
```

#### error
```
ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
```

https://developer.apple.com/documentation/coreservices/klsapplicationnotfounderr

**Comment by aliariff** [comment]
Hi @yamitake 

Thank you for giving the log. From what I see there is no error from the slim-lint extension itself.

My suggestion is to try to deactivate all of the extensions except slim-lint, and see if it is working.
And then try to activate another extension one by one, because there might be conflicted with another extension.

**Comment by yamitake** [comment]
@aliariff 

thanks for the support.

I tried it with only slim-lint extension and got the same error as before.
`ERR No application in the Launch Services database matches the input criteria`

I suspect my machine is the problem as I get the same error when I remove all extensions. I also tried reinstalling VS Code, but the results were the same.

**Comment by aliariff** [comment]
@yamitake 

Ok. If you want really debug what exactly happening in your machine, you can try to clone this project and open it in vscode and run debug.

**Comment by yamitake** [comment]
@aliariff 

Thank you very much. I will report to you when it is resolved.
